<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Daisy Larson',
                'email' => 'hschmitt@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'lBlXETPond',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Madge Mayer',
                'email' => 'santiago81@example.com',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'vXwQETFZ8Q',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Westley Kuhn',
                'email' => 'nathen34@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'ZZ2iTPGc3M',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Miss Dianna Wyman',
                'email' => 'maci.jacobi@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => '3JvtnfsrD3',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Dr. Raphael Boehm',
                'email' => 'jonathan.thiel@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'dCjBniSf13',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Ward Lowe',
                'email' => 'ziemann.raleigh@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 't445AVWTXb',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Ms. Megane Grant IV',
                'email' => 'okemmer@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'qu0JIdoyZl',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Lucienne Reilly I',
                'email' => 'greta75@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'ZoukrxT5Xf',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Saul Rippin',
                'email' => 'bins.vilma@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'Leq5E415P0',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Dr. Miller Nikolaus V',
                'email' => 'felicita95@example.com',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'hXNF568OHx',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Mr. Baylee Goldner',
                'email' => 'araceli97@example.com',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'upUyFIKwX8',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Pietro Fisher',
                'email' => 'cjaskolski@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'wdLZfgQTLd',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Bonnie Wilkinson',
                'email' => 'nhuel@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'KXbmsMKujh',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Golda Okuneva',
                'email' => 'mdavis@example.com',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'xLGUg87ttk',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Gilberto Schimmel',
                'email' => 'larson.joel@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'Z0ohbEgfAg',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Ernestina Kuvalis IV',
                'email' => 'kasandra.boyle@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'JC0VTk0Mgo',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Mr. Daron Crona DDS',
                'email' => 'wyman56@example.com',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => '0DUIQIcEft',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Orlo Bahringer',
                'email' => 'wweissnat@example.com',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'MxX6UCOxQy',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Hilda Pagac',
                'email' => 'ahane@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'mipXAmZS4g',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Kaylin Reilly',
                'email' => 'hessel.lew@example.com',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'lqskYR1aNZ',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Jeanette Wiza',
                'email' => 'vgutmann@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'syluwktWac',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Mr. Dagmar Fahey DVM',
                'email' => 'tierra.keebler@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'mFj51aC43g',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Karen Trantow Sr.',
                'email' => 'runte.kayla@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'meWIFjbKzm',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Zelma Kling',
                'email' => 'zmorissette@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'lekf6hnQ2Q',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Dr. Libby Doyle Jr.',
                'email' => 'lmiller@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => '7DNKmegHy8',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Toney Walker',
                'email' => 'jake81@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => '1CKasAmfBF',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Mr. Deontae Hessel IV',
                'email' => 'hilpert.adele@example.org',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'dQKNS7ggC6',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Xander Fisher',
                'email' => 'ceffertz@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'yXDqkW0180',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Chanel Wilderman',
                'email' => 'orlando.veum@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'CwaXhHhz3k',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Melvina Buckridge',
                'email' => 'shanon13@example.net',
                'email_verified_at' => '2022-09-05 07:03:59',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => 'rY3lK7iIhS',
                'created_at' => '2022-09-05 07:03:59',
                'updated_at' => '2022-09-05 07:03:59',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'mubashir2394@gmail.com',
                'email' => 'mubashir2394@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$KTwTA1cqgziJQc.d1M/6UO50yhcaNNw..5YaRdRbaMO56HSNvGxf.',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-09-06 17:38:16',
                'updated_at' => '2022-09-06 17:38:16',
            ),
        ));
        
        
    }
}